### PR TITLE
Ad-hoc IP Gathering and Support Manual Device List

### PR DESCRIPTION
**Pull request by Kneckter**
This PR contains the code to get an IP address when a reopen request comes in, instead of gathering all of them at the initial launch. This will help with IP changes that happen when a device is rebooted. 

A new config option was added to support a manual list of device info in case people cannot get cfgutil to work. A second config option was added to specify if IP address should be read from the manual list or to allow the script to handle them.

I also formatted the script's spacing so you may want to use the option to ignore whitespace changes if you are reviewing.

### CODE REVIEW

**Comment by kbtbc** [comment]
Can we make the json format ouput of cfgutil be an option?     All my macminis are stuck on HighSierra and I don't think it's possible to update AC2 to get the json format to work.

**Comment by Kneckter** [comment]
I'm not following what you are asking for. If you use the manual_list config option, the output of cfgutil is optional and requires the use of the device.json file instead. You would fill-in the device.json file manually with the needed keys.

**Comment by Gladiator10864** [comment]
Started using this PR about 24 hours ago and it's so far made a world of difference for outages.

**Comment by versx** [comment]
> Can we make the json format ouput of cfgutil be optional? All my macminis are stuck on HighSierra and I don't think it's possible to update AC2 to get the json format to work.

That's literally the purpose of this PR 😛

**Pull request merged**
